<?php 
  if(!defined('PATH_HD'))exit;
$cache_d704bb352eb7a5ef9dafbed14ea1791e = Array
	(
	0=>Array
		(
		'field'=>'rbid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'name',
		'type'=>'varchar(6)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'gender',
		'type'=>'tinyint(1) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'birthday',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'marital_status',
		'type'=>'tinyint(1) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'work_exp',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'origin_provice',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'cert_type',
		'type'=>'tinyint(3) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'telephone',
		'type'=>'varchar(12)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'link_provice',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'id_number',
		'type'=>'varchar(20)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'resume_id',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'profile',
		'type'=>'varchar(100)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'link_city',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'link_town',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	15=>Array
		(
		'field'=>'origin_city',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	16=>Array
		(
		'field'=>'origin_town',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	17=>Array
		(
		'field'=>'self_eval',
		'type'=>'varchar(200)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	18=>Array
		(
		'field'=>'work_type',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	19=>Array
		(
		'field'=>'hope_city',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	20=>Array
		(
		'field'=>'hope_town',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	21=>Array
		(
		'field'=>'hope_provice',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	22=>Array
		(
		'field'=>'hope_career_t',
		'type'=>'varchar(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	23=>Array
		(
		'field'=>'hope_career',
		'type'=>'varchar(30)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	24=>Array
		(
		'field'=>'hope_industry',
		'type'=>'varchar(30)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	25=>Array
		(
		'field'=>'hope_salary',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	26=>Array
		(
		'field'=>'uid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	27=>Array
		(
		'field'=>'address',
		'type'=>'varchar(25)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	28=>Array
		(
		'field'=>'link_email',
		'type'=>'varchar(30)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>