<?php 
  if(!defined('PATH_HD'))exit;
$cache_eb83d9789e2855564318ea910be31a5f = Array
	(
	0=>Array
		(
		'field'=>'uid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>''
		),
	1=>Array
		(
		'field'=>'name',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'company_industry',
		'type'=>'varchar(70)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'company_property',
		'type'=>'tinyint(3) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'company_scope',
		'type'=>'tinyint(3) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'desc',
		'type'=>'varchar(300)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'address',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'city',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'town',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'street',
		'type'=>'varchar(45)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'logo',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'contact_person',
		'type'=>'varchar(6)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'link_email',
		'type'=>'varchar(40)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'contact_tel',
		'type'=>'varchar(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'license',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	15=>Array
		(
		'field'=>'mobile_verify',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	16=>Array
		(
		'field'=>'license_verify',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	17=>Array
		(
		'field'=>'tpl_style',
		'type'=>'varchar(20)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'skyblue',
		'extra'=>''
		)
	);
?>