<?php 
  if(!defined('PATH_HD'))exit;
$cache_9170c15660e898913b007a5512ceb110 = Array
	(
	0=>Array
		(
		'field'=>'mfid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'field_name',
		'type'=>'varchar(60)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'title',
		'type'=>'varchar(45)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'field_null',
		'type'=>'tinyint(1)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'rule',
		'type'=>'varchar(540)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'dmid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'field_type',
		'type'=>'varchar(25)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'default_val',
		'type'=>'varchar(700)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'width',
		'type'=>'varchar(4)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'height',
		'type'=>'varchar(4)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'length',
		'type'=>'varchar(30)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'html_attr',
		'type'=>'varchar(60)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'sort',
		'type'=>'smallint(4)',
		'null'=>'NO',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'js_event',
		'type'=>'varchar(160)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'field_tips',
		'type'=>'varchar(60)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	15=>Array
		(
		'field'=>'error_tips',
		'type'=>'varchar(60)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	16=>Array
		(
		'field'=>'state',
		'type'=>'tinyint(1) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	17=>Array
		(
		'field'=>'data',
		'type'=>'varchar(300)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	18=>Array
		(
		'field'=>'join_index',
		'type'=>'tinyint(1)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	19=>Array
		(
		'field'=>'lcgid',
		'type'=>'varchar(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	20=>Array
		(
		'field'=>'attached',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	21=>Array
		(
		'field'=>'linkage_style',
		'type'=>'tinyint(1)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	22=>Array
		(
		'field'=>'editor_style',
		'type'=>'tinyint(2) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	23=>Array
		(
		'field'=>'show_field',
		'type'=>'tinyint(3) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	24=>Array
		(
		'field'=>'setting',
		'type'=>'varchar(300)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	25=>Array
		(
		'field'=>'js_rule',
		'type'=>'varchar(300)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	26=>Array
		(
		'field'=>'is_sys',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>