<?php 
  if(!defined('PATH_HD'))exit;
$cache_213559283399052de70c0f08308c054e = Array
	(
	0=>Array
		(
		'field'=>'lcgid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'cate_title',
		'type'=>'varchar(45)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'is_sys',
		'type'=>'tinyint(1)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>