<?php 
  if(!defined('PATH_HD'))exit;
$cache_bf2ba3a2171b1eb8e4fc67b3f5647f43 = Array
	(
	0=>Array
		(
		'field'=>'vrid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'regexp',
		'type'=>'varchar(250)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'title',
		'type'=>'varchar(20)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>