<?php 
  if(!defined('PATH_HD'))exit;
$cache_bfeb3cdf494847fee6bec5f24e74fe27 = Array
	(
	0=>Array
		(
		'field'=>'key_id',
		'type'=>'char(32)',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>''
		),
	1=>Array
		(
		'field'=>'user_id',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>1,
		'default'=>'0',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'user_agent',
		'type'=>'varchar(150)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'last_ip',
		'type'=>'varchar(40)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'last_login',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>