<?php 
  if(!defined('PATH_HD'))exit;
$cache_cb44fb96e075430054d794c3d7d8cb2b = Array
	(
	0=>Array
		(
		'field'=>'ftid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'name',
		'type'=>'varchar(60)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'title',
		'type'=>'varchar(45)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>