<?php 
  if(!defined('PATH_HD'))exit;
$cache_4dcf30308970a1f116640a5b01c77196 = Array
	(
	0=>Array
		(
		'field'=>'uid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'username',
		'type'=>'char(15)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'password',
		'type'=>'char(45)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'email',
		'type'=>'varchar(45)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'banned',
		'type'=>'tinyint(1)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'ban_reason',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'newpass',
		'type'=>'varchar(34)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'newpass_key',
		'type'=>'varchar(32)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'newpass_time',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'created',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'last_ip',
		'type'=>'varchar(40)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'last_login',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'email_verify',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>