<?php if(!defined("PATH_HD")){exit("禁止访问");} return array (
  'title' => 
  array (
    'mfid' => '99',
    'field_name' => 'title',
    'title' => '标题',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"30"}',
    'dmid' => '8',
    'field_type' => 'switch',
    'default_val' => '',
    'width' => '0',
    'height' => '0',
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => 
    array (
      '兴趣爱好' => '兴趣爱好',
      '获得荣誉' => '获得荣誉',
      '专业组织' => '专业组织',
      '著作/论文' => '著作/论文',
      '专利' => '专利',
      '宗教信仰' => '宗教信仰',
      '特长职业目标' => '特长职业目标',
      '特殊技能' => '特殊技能',
      '社会活动' => '社会活动',
      '荣誉' => '荣誉',
      '推荐信' => '推荐信',
      '其他' => '其他',
    ),
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => 
    array (
      'type' => 'option',
      'fieldtype' => 'VARCHAR',
      'frontend' => '2',
    ),
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'content' => 
  array (
    'mfid' => '100',
    'field_name' => 'content',
    'title' => '内容',
    'field_null' => '1',
    'rule' => '{"maxlength":"300"}',
    'dmid' => '8',
    'field_type' => 'textarea',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '300',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'resume_id' => 
  array (
    'mfid' => '103',
    'field_name' => 'resume_id',
    'title' => '简历ID',
    'field_null' => '1',
    'rule' => '[]',
    'dmid' => '8',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '0',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '0',
  ),
  'uid' => 
  array (
    'mfid' => '123',
    'field_name' => 'uid',
    'title' => '用户ID',
    'field_null' => '1',
    'rule' => '{"required":"true"}',
    'dmid' => '8',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => '0',
    'height' => '0',
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '0',
    'data' => '0',
    'join_index' => '1',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => 
    array (
    ),
    'js_rule' => NULL,
    'is_sys' => '0',
  ),
);