<?php if(!defined("PATH_HD")){exit("禁止访问");} return array (
  'edu_start' => 
  array (
    'mfid' => '84',
    'field_name' => 'edu_start',
    'title' => '开始时间',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"20"}',
    'dmid' => '7',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '20',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => 'onfocus="WdatePicker({dateFmt:\'yyyy-MM-dd\',autoPickDate:true})"',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'resume_id' => 
  array (
    'mfid' => '102',
    'field_name' => 'resume_id',
    'title' => '简历ID',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"10"}',
    'dmid' => '7',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => '0',
    'height' => '0',
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '0',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => 
    array (
    ),
    'js_rule' => NULL,
    'is_sys' => '0',
  ),
  'uid' => 
  array (
    'mfid' => '122',
    'field_name' => 'uid',
    'title' => '用户ID',
    'field_null' => '1',
    'rule' => '[]',
    'dmid' => '7',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => '0',
    'height' => '0',
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '0',
    'data' => '0',
    'join_index' => '1',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '0',
  ),
  'edu_end' => 
  array (
    'mfid' => '86',
    'field_name' => 'edu_end',
    'title' => '结束时间',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"10"}',
    'dmid' => '7',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '10',
    'html_attr' => '',
    'sort' => '2',
    'js_event' => 'onfocus="WdatePicker({dateFmt:\'yyyy-MM-dd\',autoPickDate:true})"',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'school' => 
  array (
    'mfid' => '87',
    'field_name' => 'school',
    'title' => '学校名称',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"30"}',
    'dmid' => '7',
    'field_type' => 'input_varchar',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '30',
    'html_attr' => '',
    'sort' => '3',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'major' => 
  array (
    'mfid' => '88',
    'field_name' => 'major',
    'title' => '专业名称',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"30"}',
    'dmid' => '7',
    'field_type' => 'input_varchar',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '30',
    'html_attr' => '',
    'sort' => '4',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'degree' => 
  array (
    'mfid' => '85',
    'field_name' => 'degree',
    'title' => '学历',
    'field_null' => '1',
    'rule' => '{"required":"true"}',
    'dmid' => '7',
    'field_type' => 'switch',
    'default_val' => '1',
    'width' => NULL,
    'height' => NULL,
    'length' => '',
    'html_attr' => '',
    'sort' => '8',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => 
    array (
      1 => '初中',
      2 => '高中',
      3 => '中专',
      4 => '中技',
      5 => '大专',
      6 => '本科',
      7 => '硕士',
      8 => 'MBA',
      9 => 'EMBA',
      10 => '博士',
      11 => '其他',
    ),
    'join_index' => '1',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => 
    array (
      'type' => 'option',
      'fieldtype' => 'TINYINT',
      'unsigned' => 'UNSIGNED',
      'frontend' => '2',
    ),
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
);