<?php if(!defined("PATH_HD")){exit("禁止访问");} return array (
  'industry' => 
  array (
    'mfid' => '92',
    'field_name' => 'industry',
    'title' => '公司行业',
    'field_null' => '1',
    'rule' => '{"required":"true"}',
    'dmid' => '12',
    'field_type' => 'linkage',
    'default_val' => '',
    'width' => '0',
    'height' => '0',
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '3',
    'attached' => '[]',
    'linkage_style' => '2',
    'editor_style' => '0',
    'show_field' => '1',
    'setting' => 
    array (
    ),
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'department' => 
  array (
    'mfid' => '93',
    'field_name' => 'department',
    'title' => '所在的部门',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"10"}',
    'dmid' => '12',
    'field_type' => 'input_varchar',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'job_name' => 
  array (
    'mfid' => '94',
    'field_name' => 'job_name',
    'title' => '职位名称',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"15"}',
    'dmid' => '12',
    'field_type' => 'input_varchar',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '15',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'job_start' => 
  array (
    'mfid' => '95',
    'field_name' => 'job_start',
    'title' => '工作时间（开始）',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"10"}',
    'dmid' => '12',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => 'onfocus="WdatePicker()"',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'job_end' => 
  array (
    'mfid' => '96',
    'field_name' => 'job_end',
    'title' => '工作时间（结束）',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"10"}',
    'dmid' => '12',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => 'onfocus="WdatePicker()"',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'resume_id' => 
  array (
    'mfid' => '124',
    'field_name' => 'resume_id',
    'title' => '简历id',
    'field_null' => '1',
    'rule' => '[]',
    'dmid' => '12',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => '0',
    'height' => '0',
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '0',
    'data' => '0',
    'join_index' => '1',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '0',
  ),
  'uid' => 
  array (
    'mfid' => '125',
    'field_name' => 'uid',
    'title' => '用户ID',
    'field_null' => '1',
    'rule' => '[]',
    'dmid' => '12',
    'field_type' => 'input_int',
    'default_val' => '',
    'width' => '0',
    'height' => '0',
    'length' => '10',
    'html_attr' => '',
    'sort' => '1',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '0',
    'data' => '0',
    'join_index' => '1',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '0',
  ),
  'job_desc' => 
  array (
    'mfid' => '98',
    'field_name' => 'job_desc',
    'title' => '工作描述',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"250"}',
    'dmid' => '12',
    'field_type' => 'textarea',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '250',
    'html_attr' => '',
    'sort' => '6',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'salary' => 
  array (
    'mfid' => '97',
    'field_name' => 'salary',
    'title' => '职位月薪',
    'field_null' => '1',
    'rule' => '{"required":"true"}',
    'dmid' => '12',
    'field_type' => 'switch',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '',
    'html_attr' => '',
    'sort' => '11',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => 
    array (
      1000 => '1000元/月以下',
      100002000 => '1000-2000元/月',
      200104000 => '2001-4000元/月',
      400106000 => '4001-6000元/月',
      600108000 => '6001-8000元/月',
      800110000 => '8001-10000元/月',
      1000115000 => '10001-15000元/月',
      1500025000 => '15000-25000元/月',
      '2500000000' => '25000元/月以上',
    ),
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => 
    array (
      'type' => 'option',
      'fieldtype' => 'TINYINT',
      'unsigned' => 'UNSIGNED',
      'frontend' => '2',
    ),
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'company_name' => 
  array (
    'mfid' => '89',
    'field_name' => 'company_name',
    'title' => '公司名称',
    'field_null' => '1',
    'rule' => '{"required":"true","maxlength":"30"}',
    'dmid' => '12',
    'field_type' => 'input_varchar',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '30',
    'html_attr' => '',
    'sort' => '18',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => '0',
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => NULL,
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'company_property' => 
  array (
    'mfid' => '90',
    'field_name' => 'company_property',
    'title' => '公司性质',
    'field_null' => '1',
    'rule' => '{"required":"true"}',
    'dmid' => '12',
    'field_type' => 'switch',
    'default_val' => '',
    'width' => NULL,
    'height' => NULL,
    'length' => '',
    'html_attr' => '',
    'sort' => '19',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => 
    array (
      1 => '国企',
      2 => '外商独资',
      3 => '代表处',
      4 => '合资',
      5 => '民营',
      6 => '股份制企业',
      7 => '上市公司',
      8 => '国家机关',
      9 => '事业单位',
      10 => '其它',
    ),
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => 
    array (
      'type' => 'option',
      'fieldtype' => 'TINYINT',
      'unsigned' => 'UNSIGNED',
      'frontend' => '2',
    ),
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
  'company_scope' => 
  array (
    'mfid' => '91',
    'field_name' => 'company_scope',
    'title' => '公司规模',
    'field_null' => '1',
    'rule' => '[]',
    'dmid' => '12',
    'field_type' => 'switch',
    'default_val' => '1',
    'width' => NULL,
    'height' => NULL,
    'length' => '',
    'html_attr' => '',
    'sort' => '21',
    'js_event' => '',
    'field_tips' => '',
    'error_tips' => '',
    'state' => '1',
    'data' => 
    array (
      1 => '20人以下',
      2 => '20-99人',
      3 => '100-499人',
      4 => '500-999人',
      5 => '1000-9999人',
      6 => '10000人以上',
    ),
    'join_index' => '0',
    'lcgid' => '0',
    'attached' => NULL,
    'linkage_style' => NULL,
    'editor_style' => '0',
    'show_field' => '0',
    'setting' => 
    array (
      'type' => 'option',
      'fieldtype' => 'TINYINT',
      'unsigned' => 'UNSIGNED',
      'frontend' => '2',
    ),
    'js_rule' => NULL,
    'is_sys' => '1',
  ),
);